quarkus.cache.caffeine.libseq-cache.maximum-size=100000
quarkus.cache.caffeine.libseq-cache.expire-after-write=10m

quarkus.smallrye-openapi.info-title=Labseq API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=## This API serves an endpoint that returns the a value of the Labseq Sequence, defined as follows: \n\nn=0 => l(0) = 0\n\n n=1 => l(1) = 1\n\n n=2 => l(2) = 0\n\n n=3 => l(3) = 1\n\n n>3 => l(n) = l(n-4) + l(n-3)\n 
quarkus.smallrye-openapi.info-contact-email=${SWAGGER_CONTACT_EMAIL}
quarkus.smallrye-openapi.info-contact-name=${SWAGGER_CONTACT_NAME}
quarkus.smallrye-openapi.info-contact-url=${SWAGGER_CONTACT_URL}
quarkus.smallrye-openapi.info-license-name=MIT License
quarkus.smallrye-openapi.info-license-url=https://mit-license.org/

quarkus.swagger-ui.always-include=true
# quarkus.swagger-ui.path=swagger-ui

quarkus.smallrye-openapi.path=/g/openapi
